---
- name: Installing Prometheus & Grafana
  hosts: 10.183.133.231
  become: true
  tasks:
    - name: Update system
      apt:
        update_cache: yes

    - name: Upgrade system
      apt:
        upgrade: dist

    - name: Copying docker compose file
      copy:
        src: docker-prometheus-grafana
        dest: /home/ubuntu/

    - name: Copying prometheus.yml file
      copy:
        src: files/prometheus.yml
        dest: /home/ubuntu/

    - name: Run compose up
      shell:
        cmd: "docker-compose -f docker-compose.yml up -d"
        chdir: /home/ubuntu/
    
    - name: Change grafana folder permisiion
      shell: "sudo chown 1000:1000 grafana/data"
      args:
        executable: /bin/bash