---
- name: Setup Frontend
  hosts: 10.183.133.25
  become: true
  tasks:
    - name: Update system
      apt:
        update_cache: yes

    - name: Upgrade system
      apt:
        upgrade: dist

    - name: Remove current apps
      shell: "sudo rm -r dumbflix-frontend"
      args:
        executable: /bin/bash

    - name: Clone Dumbflix Apps
      shell: "git clone https://github.com/ridwan094/dumbflix-frontend.git"
      args:
        executable: /bin/bash

    - name: Install python-pip
      apt:
        name: python3-pip
        state: present

    - name: Pip install docker
      shell: pip install docker
      args:
        executable: /bin/bash

    - name: Log into Dockerhub
      community.docker.docker_login:
        username: rainover922
        password: nabilah@12

    - name: Docker pull frontend
      shell: docker pull rainover922/frontend:1.0
      args:
        executable: /bin/bash

    - name: Copy Dockerfile frontend
      copy:
        src: frontend/Dockerfile
        dest: /home/ubuntu/dumbflix-frontend

    - name: Copy docker-compose frontend
      copy:
        src: frontend/docker-compose.yml
        dest: /home/ubuntu/dumbflix-frontend

    - name: Run compose up
      shell:
        cmd: "docker-compose -f docker-compose.yml up -d"
        chdir: /home/ubuntu/dumbflix-frontend 