version: '3.9'
services:
  backend:
    image: rainover922/backend:1.0
    container_name: backend
    ports:
      - 5000:5000
  
  db:
    image: mysql:5.7
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=Database123!
      - MYSQL_DATABASE=dumbflix
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - /home/ubuntu/db-data/dumbflix:/var/lib/mysql
