prometheus.yml
---
global:
  scrape_interval: 10m

scrape_configs:
  - job_name: "prometheus-metrics"
    scrape_interval: 5m
    static_configs:
      - targets: ['10.183.133.231:9090']
  - job_name: "node_exporter_metrics"
    scrape_interval: 5m
    scrape_timeout: 1m
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [''10.183.133.231:9100'','10.183.133.25:9100','10.183.133.18:9100','10.183.133.86:9100','10.183.133.30:9100']
  - job_name: "cAdvisor"
    static_configs:
      - targets: ['10.183.133.231:8080']